// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IssueDetails: typeof import('./components/IssueDetails.vue')['default']
    IssueItem: typeof import('./components/IssueItem.vue')['default']
    IssuesList: typeof import('./components/IssuesList.vue')['default']
    Label: typeof import('./components/Label.vue')['default']
    LabelList: typeof import('./components/LabelList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
